#include "iRel_FCDefs.h"
#ifdef IREL_FC_FUNC_

#define iRel_getErrorType IREL_FC_FUNC_( irel_geterrortype, IREL_GETERRORTYPE )
#define iRel_getDescription IREL_FC_FUNC_( irel_getdescription, IREL_GETDESCRIPTION )
#define iRel_create IREL_FC_FUNC_( irel_create, IREL_CREATE )
#define iRel_destroy IREL_FC_FUNC_( irel_destroy, IREL_DESTROY )
#define iRel_createPair IREL_FC_FUNC_( irel_createpair, IREL_CREATEPAIR )
#define iRel_getPairInfo IREL_FC_FUNC_( irel_getpairinfo, IREL_GETPAIRINFO )
#define iRel_changePairType IREL_FC_FUNC_( irel_changepairtype, IREL_CHANGEPAIRTYPE )
#define iRel_changePairStatus IREL_FC_FUNC_( irel_changepairstatus, IREL_CHANGEPAIRSTATUS )
#define iRel_destroyPair IREL_FC_FUNC_( irel_destroypair, IREL_DESTROYPAIR )
#define iRel_findPairs IREL_FC_FUNC_( irel_findpairs, IREL_FINDPAIRS )
#define iRel_setEntEntRelation IREL_FC_FUNC_( irel_setententrelation, IREL_SETENTENTRELATION )
#define iRel_setEntSetRelation IREL_FC_FUNC_( irel_setentsetrelation, IREL_SETENTSETRELATION )
#define iRel_setSetEntRelation IREL_FC_FUNC_( irel_setsetentrelation, IREL_SETSETENTRELATION )
#define iRel_setSetSetRelation IREL_FC_FUNC_( irel_setsetsetrelation, IREL_SETSETSETRELATION )
#define iRel_setEntArrEntArrRelation IREL_FC_FUNC_( irel_setentarrentarrrelation, IREL_SETENTARRENTARRRELATION )
#define iRel_setSetArrEntArrRelation IREL_FC_FUNC_( irel_setsetarrentarrrelation, IREL_SETSETARRENTARRRELATION )
#define iRel_setEntArrSetArrRelation IREL_FC_FUNC_( irel_setentarrsetarrrelation, IREL_SETENTARRSETARRRELATION )
#define iRel_setSetArrSetArrRelation IREL_FC_FUNC_( irel_setsetarrsetarrrelation, IREL_SETSETARRSETARRRELATION )
#define iRel_getEntEntRelation IREL_FC_FUNC_( irel_getententrelation, IREL_GETENTENTRELATION )
#define iRel_getEntSetRelation IREL_FC_FUNC_( irel_getentsetrelation, IREL_GETENTSETRELATION )
#define iRel_getSetEntRelation IREL_FC_FUNC_( irel_getsetentrelation, IREL_GETSETENTRELATION )
#define iRel_getSetSetRelation IREL_FC_FUNC_( irel_getsetsetrelation, IREL_GETSETSETRELATION )
#define iRel_getEntSetIterRelation IREL_FC_FUNC_( irel_getentsetiterrelation, IREL_GETENTSETITERRELATION )
#define iRel_getEntArrEntArrRelation IREL_FC_FUNC_( irel_getentarrentarrrelation, IREL_GETENTARRENTARRRELATION )
#define iRel_getEntArrSetArrRelation IREL_FC_FUNC_( irel_getentarrsetarrrelation, IREL_GETENTARRSETARRRELATION )
#define iRel_getSetArrEntArrRelation IREL_FC_FUNC_( irel_getsetarrentarrrelation, IREL_GETSETARRENTARRRELATION )
#define iRel_getSetArrSetArrRelation IREL_FC_FUNC_( irel_getsetarrsetarrrelation, IREL_GETSETARRSETARRRELATION )
#define iRel_getEntArrSetIterArrRelation IREL_FC_FUNC_( irel_getentarrsetiterarrrelation, IREL_GETENTARRSETITERARRRELATION )
#define iRel_rmvEntRelation IREL_FC_FUNC_( irel_rmventrelation, IREL_RMVENTRELATION )
#define iRel_rmvSetRelation IREL_FC_FUNC_( irel_rmvsetrelation, IREL_RMVSETRELATION )
#define iRel_rmvEntArrRelation IREL_FC_FUNC_( irel_rmventarrrelation, IREL_RMVENTARRRELATION )
#define iRel_rmvSetArrRelation IREL_FC_FUNC_( irel_rmvsetarrrelation, IREL_RMVSETARRRELATION )
#define iRel_inferAllRelations IREL_FC_FUNC_( irel_inferallrelations, IREL_INFERALLRELATIONS )
#define iRel_inferAllRelationsAndType IREL_FC_FUNC_( irel_inferallrelationsandtype, IREL_INFERALLRELATIONSANDTYPE )
#define iRel_inferEntRelations IREL_FC_FUNC_( irel_inferentrelations, IREL_INFERENTRELATIONS )
#define iRel_inferSetRelations IREL_FC_FUNC_( irel_infersetrelations, IREL_INFERSETRELATIONS )
#define iRel_inferEntArrRelations IREL_FC_FUNC_( irel_inferentarrrelations, IREL_INFERENTARRRELATIONS )
#define iRel_inferSetArrRelations IREL_FC_FUNC_( irel_infersetarrrelations, IREL_INFERSETARRRELATIONS )

#endif
